services:
  - type: web
    name: mini-blogging-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        value: file:./prisma/prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

